// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: getput.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Get_PutClient is the client API for Get_Put service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Get_PutClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
}

type get_PutClient struct {
	cc grpc.ClientConnInterface
}

func NewGet_PutClient(cc grpc.ClientConnInterface) Get_PutClient {
	return &get_PutClient{cc}
}

func (c *get_PutClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/api.Get_Put/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *get_PutClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, "/api.Get_Put/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Get_PutServer is the server API for Get_Put service.
// All implementations must embed UnimplementedGet_PutServer
// for forward compatibility
type Get_PutServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Put(context.Context, *PutRequest) (*PutResponse, error)
	mustEmbedUnimplementedGet_PutServer()
}

// UnimplementedGet_PutServer must be embedded to have forward compatible implementations.
type UnimplementedGet_PutServer struct {
}

func (UnimplementedGet_PutServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGet_PutServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedGet_PutServer) mustEmbedUnimplementedGet_PutServer() {}

// UnsafeGet_PutServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Get_PutServer will
// result in compilation errors.
type UnsafeGet_PutServer interface {
	mustEmbedUnimplementedGet_PutServer()
}

func RegisterGet_PutServer(s grpc.ServiceRegistrar, srv Get_PutServer) {
	s.RegisterService(&Get_Put_ServiceDesc, srv)
}

func _Get_Put_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Get_PutServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Get_Put/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Get_PutServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Get_Put_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Get_PutServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Get_Put/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Get_PutServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Get_Put_ServiceDesc is the grpc.ServiceDesc for Get_Put service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Get_Put_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Get_Put",
	HandlerType: (*Get_PutServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Get_Put_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Get_Put_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "getput.proto",
}
